### ISSUE TITLE
cannot instantiate 'WindowsPath' on your system

### ISSUE THREAD

**Issue by PsidomPC** [fastai/fastai#1482]
**Describe the bug**

Installed fastai on the python:3.7 image but it fails to load the model:

> empty_data = ImageDataBunch.load_empty(modelPath)
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 649, in _databunch_load_empty
> sd = LabelLists.load_empty(path, fn=fname)
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 513, in load_empty
> state = pickle.load(open(path/fn, 'rb'))
>   File "/usr/local/lib/python3.7/pathlib.py", line 997, in __new__
>  % (cls.__name__,))
> NotImplementedError: cannot instantiate 'WindowsPath' on your system

**Provide your installation details**

```text
=== Software ===
python       : 3.7.2
fastai       : 1.0.40
fastprogress : 0.1.18
torch        : 1.0.0
torch cuda   : 9.0.176 / is **Not available**

=== Hardware ===
No GPUs available

=== Environment ===
platform     : Linux-4.9.125-linuxkit-x86_64-with-debian-9.6
distro       : #1 SMP Fri Sep 7 08:20:28 UTC 2018
conda env    : Unknown
python       : /usr/local/bin/python
sys.path     :
/usr/local/lib/python37.zip
/usr/local/lib/python3.7
/usr/local/lib/python3.7/lib-dynload
/usr/local/lib/python3.7/site-packages
no supported gpus found on this system
```

**To Reproduce**
Try build this docker file and then run it:

```
FROM python:3.7

WORKDIR /app

RUN pip3 install flask flask-cors gunicorn
RUN pip3 install torch torchvision
RUN pip3 install fastai

COPY ./src /app/src
COPY ./dist /app/dist

CMD gunicorn --bind 0.0.0.0:$PORT src.app:app
```

**Expected behavior**
The model should load and predict correctly.

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
It seems it's linked to the pathlib library, can you use it properly?

**Comment by PsidomPC** [comment]
I did some simple debug; the fail actually happens at `pickle.load` and I have tried to use either a string or a Path for the `modelPath` and both not working. I am not sure if there's an option for me to pass in the path parameter in a different way.

**Comment by PsidomPC** [comment]
Basically I tried these two ways to pass in the model path:

```
>>> modelPath = Path('/app/src/standford_data_make')
>>> empty_data = ImageDataBunch.load_empty(modelPath)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 649, in _databunch_load_empty
>     sd = LabelLists.load_empty(path, fn=fname)
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 513, in load_empty
>     state = pickle.load(open(path/fn, 'rb'))
>   File "/usr/local/lib/python3.7/pathlib.py", line 997, in __new__
>     % (cls.__name__,))
> NotImplementedError: cannot instantiate 'WindowsPath' on your system

```
>>> modelPath = '/app/src/standford_data_make'
>>> empty_data = ImageDataBunch.load_empty(modelPath)
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 649, in _databunch_load_empty
>     sd = LabelLists.load_empty(path, fn=fname)
>   File "/usr/local/lib/python3.7/site-packages/fastai/data_block.py", line 513, in load_empty
>     state = pickle.load(open(path/fn, 'rb'))
> TypeError: unsupported operand type(s) for /: 'str' and 'str'

**Comment by sgugger** [comment]
Yes, the fail happens in the pickle.load but it may be the `open(path/fn, 'rb')` that causes it. Can you do open(path/'export.pkl','rb') without error?

**Comment by sgugger** [comment]
Ok, so it can open it but not unpickle it. Could you share the code you used to create that `export.pkl` file?

**Comment by PsidomPC** [comment]
I use `data.export` to create the `export.pkl` and also yes this is done in windows, which seems to give me some idea why the error. But is there a fix for this? How can I export `export.pkl` in windows and then load it back up in a linux system?

```
data = ImageDataBunch.from_folder('./standford_data/', ds_tfms=get_transforms(), size=224, bs=8)
data.normalize(imagenet_stats)
data.export()
```

**Comment by sgugger** [comment]
No, you're using two different serializations: you should use `learn.export()` with `load_learner` and `data.load_empty` with `data.export`.

**Comment by PsidomPC** [comment]
I'm not sure I fully understand, this is my model / data folder:

```
standford_data_make:
    models:
        myModel
    export.pkl
```

From my understanding, `ImageDataBunch.from_folder` is loading from `export.pkl` to get trained data property:

```
  modelPath = Path('/app/src/standford_data_make')
  empty_data = ImageDataBunch.load_empty(modelPath)
  learn = create_cnn(empty_data, models.resnet152)
  model = learn.load(modelPath/'carmakemodelclassifiermodel') 
  model.predict(im)
```

This actually works on my windows machine, it fails when I try to deploy with a linux container.

**Comment by sgugger** [comment]
I think I fixed the issue by avoiding serializing the path (since it behaves differently on different systems), let me know if it works now (note that you'll need to recreate the export file on Windows before trying to load it on your linux container).

**Comment by javedsha** [comment]
@sgugger I am still getting this error. Was this fixed?
I have trained models in Linux system. But when i try to load the data_lm.pkl on windows, i get the below error:

'cannot instantiate 'PosixPath' on your system'

Code:
data_lm = load_data(path, 'data_lm.pkl', bs=bs)

Version:
Fast AI - 1.0.57

If this is not yet fixed, is there a way to mitigate this. Training on Windows is very slow, so ideal for us is to train on Linux and then just for inference use windows.

Thanks.

**Comment by sgugger** [comment]
I can't say if this is linked to this issue without knowing how you created the data in the first place and why there is a `Pathlib` object serialized with it.

**Comment by sgugger** [comment]
Looking into this, the issue is there on the data save because we serialize its path. Note that `Learner.export` and `load_learner` should work cross-platform if your problem is inference, but yeah, it won't work for `DataBunch.save`.

This is too much work to fix for v1, so this issue will be resolved in v2.

**Comment by DevangJ** [comment]
@sgugger Hey I too get the `NotImplementedError: cannot instantiate 'PosixPath' on your system` error.

For reference, I created the .pkl file in kaggle using learn.export() and am currently trying to use it in a Windows Machine. From what I can infer from above this shouldn't be creating a problem right?

**Comment by sgugger** [comment]
Yes, this is the same issue. The problem comes from the `pathlib` library that has incompatible path objects between different operating systems. You need to save/load your `Learner` object, not export it.

**Comment by belotfa** [comment]
> Appreciate and thanks for fixing this in v2.
> So if I understand it, I can still do the inference using the `load_learner()`. So, like
> 
> ```
> learn.save('first') -> Linux
> load_learner(path, 'first') -> Windows
> ```
> 
> This should unblock me, thanks will give a try.

@sgugger I tried this way :
learn.save('first') -> Windows
load_learner(path, 'first') -> Linux
And I got the error `NotImplementedError: cannot instantiate 'WindowsPath' on your system`
Any idea ?

**Comment by sgugger** [comment]
`load_learner` is the command to load an exported learner and is the one that fails. To load the model in saved with `learn.save()` you have to use `learn.load()`.

**Comment by belotfa** [comment]
Okay but if I use learn.save(), I have to recreate a DataBunch that fit the original one. Is there any way to use the pair export/load_learner ? Or a simple way to create an empty DataBunch with only the pth model ?

**Comment by sgugger** [comment]
There is the from_classes method if I remember correctly for doing that.

**Comment by rothn** [comment]
I am having the same issue with DataBunch (de)serialization. @sgugger , maybe the cure for this is an option to use lower-level APIs (e.g. passing NumPy arrays that we manage ourselves instead of dataframes)? I found it a bit strange that I had to convert my NumPy arrays to a dataframe in order to use a language model.

**Comment by belotfa** [comment]
Okay thanks a lot, I'll check this out.

**Comment by gbinnie** [comment]
I'm having similar issue when trying to load_learner on colab a learner that was exported from a Windows machine. The problem seems to be that the learner.path is serialized as pathlib.WindowsPath and when we try to deserialize the system cannot instantiate. Is there a way I can change the learner.path to a string and then export? I tried to force this, but it fails to export. Any ideas?

**Comment by Svensone** [comment]
same problem here.
training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
Any help appreciated ! thx

**Comment by gbinnie** [comment]
> same problem here.
> training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> Any help appreciated ! thx

I found a solution for this adding the below to the code:

```
import pathlib
plt = platform.system()
if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
```

**Comment by Svensone** [comment]
@gbinnie : Awesome ! It works now with your code!

big thanks from Bali !

**Comment by GotAudio** [comment]
I was trying to publish a model on HuggingFace and it failed for the same reason. gbinnie's fix solved it.  Thanks! https://huggingface.co/spaces/GotAudio/Understanding-Women

**Comment by cfmoreno** [comment]
> > same problem here.
> > training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> > Any help appreciated ! thx
> 
> I found a solution for this adding the below to the code:
> 
> ```
> import pathlib
> plt = platform.system()
> if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> ```

Just had this exact problem and your code solved it. Thank you!

**Comment by mateus-lm** [comment]
> > > same problem here.
> > > training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> > > Any help appreciated ! thx
> > 
> > 
> > I found a solution for this adding the below to the code:
> > ```
> > import pathlib
> > plt = platform.system()
> > if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> > ```
> 
> Where should we add this? I tried adding this line of code but I got an error - `Name platform is not defined`

Same error here, what's your OS ?

**Comment by srinathjayaraman** [comment]
> > > > same problem here.
> > > > training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> > > > Any help appreciated ! thx
> > > 
> > > 
> > > I found a solution for this adding the below to the code:
> > > ```
> > > import pathlib
> > > plt = platform.system()
> > > if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> > > ```
> > 
> > 
> > Where should we add this? I tried adding this line of code but I got an error - `Name platform is not defined`
> 
> Same error here, what's your OS ?
> 
> #Edit 1, I just used this below from imports, with this change it does run only in Hugging Face (I'm using Windows)
> 
> ```python
> import pathlib
> plt = platform.system()
> if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> ```

I was running this on Linux!

**Comment by sarangkashalkar** [comment]
> > same problem here.
> > training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> > Any help appreciated ! thx
> 
> I found a solution for this adding the below to the code:
> 
> ```
> import pathlib
> plt = platform.system()
> if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> ```

thanks a lot <3

**Comment by gayratqurbonov** [comment]
Menda bu holatga yechim topilmadi

**Comment by ChingizIbnVaxob** [comment]
> > same problem here.
> > training and export of fastaiV2 model on windows. created App with Streamlit. on local Windows machine running smooth. Deployed on https://share.streamlit.io/ error "NotImplementedError: cannot instantiate 'WindowsPath' on your system"
> > Any help appreciated ! thx
> 
> I found a solution for this adding the below to the code:
> 
> ```
> import pathlib
> plt = platform.system()
> if plt == 'Linux': pathlib.WindowsPath = pathlib.PosixPath
> ```

Thanks, I believe this worked before, but now this solution doesn't work!
Did somebody find another solution?
