### ISSUE TITLE
Colab Support

### ISSUE THREAD

**Issue by jtrofe** [fastai/fastai#1588]
The doc() function does not work in Google Colab. Colab doesn't seem to allow you to display HTML in outputs, so `page.page({'text/html': output})` does not do anything

I was able to make it work by replacing that line with this:

    IPython.get_ipython().run_cell_magic(u'HTML', u'', output)

**Comment by sgugger** [comment]
I believe this command is doing the same as displaying the output as markdown. What fails on colab is that it doesn't let the notebook open a new window like jupyter notebook. I think I've fixed it with this try and except block (on master) so after the next release it should work properly.

**Comment by ericricky** [comment]
Upgrading to 1.0.44.dev0 in Colab doesn't fix it for me. @jtrofe's code works for me though.
