### ISSUE TITLE
doc() does not work in Colab

### ISSUE THREAD

**Issue by pnlph** [fastai/fastai#1660]
**Describe the bug**
The help method doc() does not work in colab. On the other hand ?? is working to show the source code.

**Provide your installation details**

```text
=== Software === 
python        : 3.6.7
fastai        : 1.0.45
fastprogress  : 0.1.19
torch         : 1.0.1.post2
nvidia driver : 410.79
torch cuda    : 10.0.130 / is available
torch cudnn   : 7402 / is enabled

=== Hardware === 
nvidia gpus   : 1
torch devices : 1
  - gpu0      : 11441MB | Tesla K80

=== Environment === 
platform      : Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
distro        : #1 SMP Wed Dec 19 21:19:13 PST 2018
conda env     : Unknown
python        : /usr/bin/python3
sys.path      : 
/env/python
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/local/lib/python3.6/dist-packages/IPython/extensions
/root/.ipython
```

**To Reproduce**
Just open a colab notebook, paste and evaluate the following code:
```
from fastai import *
from fastai.vision import *
doc(accuracy)
```

**Expected behavior**
A summary of the function with a link to the source, like in the videos.

**Screenshots**

**Additional context**

**Comment by sgugger** [comment]
This should now work (note that it's not possible to pop up a new window in colab, but it will appear as the result of the cell). You will need to use master to see it until v1.0.46 is released, you can install it with:
```
!pip install git+https://github.com/fastai/fastai
```

**Comment by ericricky** [comment]
@sgugger This still does not work for me. Did you delete my previous comment? See [this notebook](https://colab.research.google.com/gist/ericricky/0ae77f6b9e88c671fde76568b819eb5d/doc_in_colab.ipynb). Note that even in my fork that fixes `doc`, the 'source' link does not work unless opened in a new tab. Can we please reopen?

**Comment by sgugger** [comment]
No, I didn't delete anything.
Your fix breaks the current behavior in jupyter notebooks (which is the environment for which this function was developed) so we can't have it that way. If colab fails silently on something it's not doing properly, we need to include some way to detect if we are in colab or a jupyter notebook to test which instruction to execute.

**Comment by ericricky** [comment]
@sgugger Sorry, thought I commented a few days ago but I must have forgotten. I'll take another look at it
