### ISSUE TITLE
basic_train.Learner() ignores the loss_func parameter

### ISSUE THREAD

**Issue by cristi-zz** [fastai/fastai#943]
**Describe the bug**

I try to instantiate a new Learner and I got the below error. This code worked sometime last week. Don't remember the exact version. However, back then, the loss_func parameter was called loss_fn. 

**To Reproduce**

```
learner = basic_train.Learner(data=data_bunch, model=seq_model,
                              loss_func=nn.CrossEntropyLoss())

```

**Expected behavior**

To instantiate a new Learner that I can fit()
**Screenshots**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-65f430282951> in <module>
     26 
     27 learner = basic_train.Learner(data=data_bunch, model=seq_model,
---> 28                               loss_func=nn.CrossEntropyLoss())
     29 
     30 

<string> in __init__(self, data, model, opt_func, loss_func, metrics, true_wd, bn_wd, wd, train_bn, path, model_dir, callback_fns, callbacks, layer_groups)

~/miniconda3/envs/tf/lib/python3.6/site-packages/fastai/basic_train.py in __post_init__(self)
    112         (self.path/self.model_dir).mkdir(parents=True, exist_ok=True)
    113         self.model = self.model.to(self.data.device)
--> 114         self.loss_func = ifnone(self.loss_func, self.data.loss_func)
    115         self.metrics=listify(self.metrics)
    116         if not self.layer_groups: self.layer_groups = [nn.Sequential(*flatten_model(self.model))]

~/miniconda3/envs/tf/lib/python3.6/site-packages/fastai/basic_data.py in __getattr__(self, k)
     91         return cls(*dls, path=path, device=device, tfms=tfms, collate_fn=collate_fn)
     92 
---> 93     def __getattr__(self,k:int)->Any: return getattr(self.train_ds, k)
     94     def holdout(self, is_test:bool=False)->DeviceDataLoader:
     95         "Returns correct holdout `Dataset` for test vs validation (`is_test`)."

AttributeError: 'TensorDataset' object has no attribute 'loss_func'


```
**Additional context**

fastai ver 1.0.11 (anaconda) python 3.6

**Comment by yayanaai** [comment]
Hello!

I encounter this error when running through `lesson5-sgd-mnist.ipynb`.
My VM is running fastai v1.0.46 (anaconda), python 3.7.1

```python
# cell 18
loss_func = nn.CrossEntropyLoss()

# cell 34
learn = Learner(data, Mnist_NN(), loss_func=loss_func, metrics=accuracy)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-34-cc98ebe3feca> in <module>
----> 1 learn = Learner(data, Mnist_NN(), loss_func=nn.CrossEntropyLoss, metrics=accuracy)

<string> in __init__(self, data, model, opt_func, loss_func, metrics, true_wd, bn_wd, wd, train_bn, path, model_dir, callback_fns, callbacks, layer_groups, add_time)

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_train.py in __post_init__(self)
    155         (self.path/self.model_dir).mkdir(parents=True, exist_ok=True)
    156         self.model = self.model.to(self.data.device)
--> 157         self.loss_func = ifnone(self.loss_func, self.data.loss_func)
    158         self.metrics=listify(self.metrics)
    159         if not self.layer_groups: self.layer_groups = [nn.Sequential(*flatten_model(self.model))]

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in __getattr__(self, k)
    120         return cls(*dls, path=path, device=device, dl_tfms=dl_tfms, collate_fn=collate_fn, no_check=no_check)
    121 
--> 122     def __getattr__(self,k:int)->Any: return getattr(self.train_dl, k)
    123     def __setstate__(self,data:Any): self.__dict__.update(data)
    124 

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in __getattr__(self, k)
     36 
     37     def __len__(self)->int: return len(self.dl)
---> 38     def __getattr__(self,k:str)->Any: return getattr(self.dl, k)
     39     def __setstate__(self,data:Any): self.__dict__.update(data)
     40 

/opt/anaconda3/lib/python3.7/site-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
     18 torch.utils.data.DataLoader.__init__ = intercept_args
     19 
---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
     21 DataLoader.__getattr__ = DataLoader___getattr__
     22 

AttributeError: 'TensorDataset' object has no attribute 'loss_func'
```

Any advise on how I may resolve this? I am happy to raise a new issue if indeed this is a bug.

Thank you.

**Comment by stas00** [comment]
short term workaround: comment out this line

`self.loss_func = ifnone(self.loss_func, self.data.loss_func)` in `fastai/basic_train.py`

**Comment by stas00** [comment]
This has to do with this weird python feature:
https://github.com/encode/django-rest-framework/issues/2108#issuecomment-73504704
so basically, `self.data.loss_func` fails (no `train_ds.y`), and instead of giving the user the traceback for that failure, python falls back to `__getattr__` and fails there with a totally wrong error.

**Comment by stas00** [comment]
fixed in https://github.com/fastai/fastai/commit/a25d1d795c0bcc3c87ed83caf232f2046c92e01f

**Comment by yayanaai** [comment]
Brilliant - thanks

**Comment by daphn3cor** [comment]
Hi guys, I still get the same error with the newest version of the notebook in colab


`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-7aa74a9f84cb> in <module>()
----> 1 learn = Learner(data, Mnist_NN(), loss_func=loss_func, metrics=accuracy)

<string> in __init__(self, data, model, opt_func, loss_func, metrics, true_wd, bn_wd, wd, train_bn, path, model_dir, callback_fns, callbacks, layer_groups, add_time)

/usr/local/lib/python3.6/dist-packages/fastai/basic_train.py in __post_init__(self)
    155         (self.path/self.model_dir).mkdir(parents=True, exist_ok=True)
    156         self.model = self.model.to(self.data.device)
--> 157         self.loss_func = ifnone(self.loss_func, self.data.loss_func)
    158         self.metrics=listify(self.metrics)
    159         if not self.layer_groups: self.layer_groups = [nn.Sequential(*flatten_model(self.model))]

/usr/local/lib/python3.6/dist-packages/fastai/basic_data.py in __getattr__(self, k)
    120         return cls(*dls, path=path, device=device, dl_tfms=dl_tfms, collate_fn=collate_fn, no_check=no_check)
    121 
--> 122     def __getattr__(self,k:int)->Any: return getattr(self.train_dl, k)
    123     def __setstate__(self,data:Any): self.__dict__.update(data)
    124 

/usr/local/lib/python3.6/dist-packages/fastai/basic_data.py in __getattr__(self, k)
     36 
     37     def __len__(self)->int: return len(self.dl)
---> 38     def __getattr__(self,k:str)->Any: return getattr(self.dl, k)
     39     def __setstate__(self,data:Any): self.__dict__.update(data)
     40 

/usr/local/lib/python3.6/dist-packages/fastai/basic_data.py in DataLoader___getattr__(dl, k)
     18 torch.utils.data.DataLoader.__init__ = intercept_args
     19 
---> 20 def DataLoader___getattr__(dl, k:str)->Any: return getattr(dl.dataset, k)
     21 DataLoader.__getattr__ = DataLoader___getattr__
     22 

AttributeError: 'TensorDataset' object has no attribute 'loss_func'`

**Comment by sgugger** [comment]
You must not have the latest version (the code I see is pre-fix). You can check your version with 
```
from fastai.utils.show_install import show_install
show_install()
```
and you can download the master version on colab with
```
!pip install git+https://github.com/fastai/fastai
```
